---
title: ''
output:
  html_document: default
  pdf_document: default
---
<p align="center"><font size="8">2017BIHomework5</font></p>
<p align="center"><font size="4">Cai Jing</font></p>

```{r}
AHP <- function (A) 
{
    l <- length(A) #l为矩阵元素的个数
    n <- floor(sqrt(l)) #n为矩阵A的列数
      if(length(A[which(A<0)])!=0){#输入的矩阵存在负值
        cat("判断矩阵内容错误，权重不能为负！")
      }
      else if(sqrt(l)-floor(sqrt(l)) != 0){
        cat("判断矩阵结构错误，无法进行一致性检验！") #输入的矩阵不满足判断矩阵
      }
      else{
        colsums = matrix(A) #求出每一列的总和
        norA <- matrix(nrow=n,ncol=n)#创建一个和A行列相同的空矩阵
        for(i in 1:n)
          norA[,i] <-A[,i]/colsums[i] #每一列的元素除以相应列的总和，得到标准两两比较矩阵norA
        rowmeans = rowMeans(norA)    #计算标准两两比较矩阵每一行的平均值
        round(norA, 4) #规定精度为小数点后四位
        if (n > 2) {
          W = matrix(rowmeans, ncol = 1) #标准两两比较矩阵每一行的平均值，即特征向量W
          AW = as.vector(A %*% W) # 将两两比较矩阵A乘其特征向量W的乘积向量化，得到赋值和向量
          la_max = sum(AW/W)/n # 每个赋值和向量除以对应的特征向量的分量，求其平均值，得出判断矩阵A的最大特征根λmax
          CI = (la_max - n)/(n - 1) #计算一致性指标CI=(λmax-n)/(n-1)
          RI = c(0, 0, 0.58, 0.9, 1.12, 1.24, 1.32, 1.41, 1.45)
          CR = CI/RI[n] #计算一致性率CR=CI/RI
          # 输出CR的值，精度为小数点后4为
          cat(" CR=", round(CR, 4), "\n")
          if (CR <= 0.1) { #如果CR<0.1，则认为该判断矩阵通过一致性检验
            cat(" 通过一致性检验！\n")
          }else{
            cat(" 未通过一致性检验！\n")
          }
    }
  }
}
```


```{r}
# Test1
AHP(matrix(c(1,5,3,1/5,1,1/3,1/3,3,1),nrow=3,ncol=3))
# Test2
AHP(matrix(c(1,8,2,3,1/8,1,1/7,1/5,1/2,7,1,1/3,1/3,5,3,1),nrow=4,ncol=4))
# Test3
AHP(matrix(c(1,1/5,1/6,5,1,1/4,6,-4,1),nrow=3,ncol=3))
# Test4
AHP(matrix(c(1,1/2,1/6,2,1,1/4),nrow=3))
# Test5
AHP(c(1,1,1/2,1/6,2,1,1/4))
```

